config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do
    
  root 'pages#home'

  ActiveAdmin.routes(self)
  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix
  devise_for :users, path: devise_prefix,
    controllers: {registrations: 'users/registrations', sessions: 'users/sessions',
      passwords: 'users/passwords', confirmations: 'users/confirmations', unlocks: 'users/unlocks'},
    path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}
  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
  end
  get devise_prefix => redirect('/#account')
  post devise_prefix => redirect('/#account')

  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'
  get '/terms' => 'pages#terms', as: 'terms'
  get '/privacy' => 'pages#privacy', as: 'privacy'
  get '/billing' => 'pages#billing', as: 'billing'
  get '/cookies' => 'pages#cookies', as: 'cookies'
  get '/copyright' => 'pages#copyright', as: 'copyright'
  get '/earnings' => 'pages#earnings', as: 'earnings'
  get '/spam' => 'pages#spam', as: 'spam'

  # OAuth
  oauth_prefix = Rails.application.config.auth.omniauth.path_prefix
  get "#{oauth_prefix}/:provider/callback" => 'users/oauth#create'
  get "#{oauth_prefix}/failure" => 'users/oauth#failure'
  get "#{oauth_prefix}/:provider" => 'users/oauth#passthru', as: 'provider_auth'
  get oauth_prefix => redirect("#{oauth_prefix}/login")

  # User
  resources :users, path: 'u', only: :show do
    resources :authentications, path: 'accounts'
  end
  get '/dashboard' => 'articles#index', as: 'user_home'

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  get 'robots.:format' => 'robots#index'

  resources :articles do 
   member do
       get :download
       get :archive
     end
     collection do 
      get :index_archive
     end
  end

  resources :users
  
end

app/models/article.rb
class Article < ActiveRecord::Base
		
	belongs_to :user
	belongs_to :writer ,:class_name => "User",:foreign_key => "writer_id"

	 scope :unassigned, -> {where("writer_id IS NULL")}
	 scope :assigned, -> {where("writer_id IS NOT NULL")}
	 scope :inprogress, -> {assigned.where(:status=>"inprogress")}
	 scope :completed, -> {assigned.where(:status=>"complete")}
	 scope :new_requested, -> {where(:status=>"new")}


	 after_create :mark_as_new

	# scope :writer, -> { where(user_type: 'writer') }
	# scope :standard_user, -> { where(user_type: 'standard') }
	# scope :approved_writer, -> { writer.where(:approved=>true)} 
	# scope :unapproved_writer,->{ writer.where(:approved=>false)}
	
	def mark_as_new
		self.update(:status=>"new")
	end

	def status_enum
		[['new', 0],['Pending',1],['InProgress',2],['Completed',3]]
	end
	def is_complete?
		self.status == "complete" ? true : false
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_authorization_check
  
  def index
    @articles = current_user.articles.where("published= ?",true)
  end

  def new
     @request_article = current_user.articles.build
  end

  def create
    @request_article = current_user.articles.build(request_article_params)
    if @request_article.save
      flash[:notice]="Request successfully submit"
      redirect_to action: :index
    end
  end

  def update
  end
 
  def show
    @article = current_user.articles.find_by_id(params[:id])
  end

  def destroy
  end

  def download
    article = Article.find(params[:id])
    # file = File.new("./public/article_files"+article.keywords+".txt",'w')
    # file.puts article.content
    # file.close
    send_data article.content, :filename => article.keywords+".txt"
    # redirect_to action: :index
  end
  def archive
     article = Article.find(params[:id])
     article.archive = true
     if article.save!
     redirect_to articles_path,:notice=>"Article Archives Successfully"
     end
  end
  def index_archive
    @article_archive = Article.where(:archive=>true)
  end
  private
  def request_article_params
    params.require(:article).permit(:keywords, :content, :ordered, :exact_kewords, :article_instruction, :no_of_article, :word_count, :fixed_delivery_time, :writer_stars, :depth_research, :specific_style, :article_topic_warning, :status, :assigned_writerm, :user_id, :writer_id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper

	def count_words(text)
		if text
		word_count = text.split.length rescue '0'
	end
	end

	def calculate_cost(text)
		if text
		word_count = text.split.length
		total_cost = 0.007*word_count
	else
		'0'
	end
	end
end

app/views/articles/destroy.html.erb
%h1 Articles#destroy
%p Find me in app/views/articles/destroy.html.haml

app/views/articles/edit.html.erb
%h1 Articles#edit
%p Find me in app/views/articles/edit.html.haml

app/views/articles/index.html.erb
 <h1 style="display:inline;">My Article Dashboard </h1> 
 <%= link_to " show archives",index_archive_articles_path%>



<table class="table table-striped">
<tr>
  <td>Ordered</td>
  <td>Keywords</td>
  <td>Word Count</td>
  <td>Cost Complete</td>
  <td> view</td>

</tr>
<% @articles.each do  |a|%>
<tr>
  <td><%=a.created_at.strftime("%m/%d/%Y") %></td>
  <td><%=a.keywords%></td>
  <td><%=count_words(a.content)%></td>
  <td><%=number_to_currency(calculate_cost(a.content), :unit => "$")%></td>
  <td><%=link_to "Detail", article_path(a)%>|<%=link_to "download", download_article_path(a)%>|
    <% if !a.archive? %>
    <%=link_to "Archive", archive_article_path(a)%></td>
    <% end %>
</tr>
<% end %>
</table>

app/views/articles/index_archive.html.erb
<h1>My Article Dashboard</h1>
<table class="table table-striped">
<tr>
  <td>Ordered</td>
  <td>Keywords</td>
  <td>Word Count</td>
  <td>Cost Complete</td>
  <td> view</td>

</tr>
<% @article_archive.each do  |a|%>
<tr>
  <td><%=a.created_at.strftime("%m/%d/%Y") %></td>
  <td><%=a.keywords%></td>
  <td><%=count_words(a.content)%></td>
  <td><%=number_to_currency(calculate_cost(a.content), :unit => "$")%></td>
  <td><%=link_to "Detail", article_path(a)%>|<%=link_to "download", download_article_path(a)%></td>
</tr>
<% end %>
</table>

s

app/views/articles/new.html.erb
<div class="container">
<div><h1> Request Articles </h1></div>                New! Request Article Rewrites
<br/>
<p>
	Requesting articles is simple. All you need to do is enter the keywords you want each article created on (one set of keywords per line), then indicate how many different articles you want created around each set of keywords. Finally, choose the minimum word count of the articles and any additional options you require.
</p>
<h2>Article Keywords:</h2>
One set of keywords per line.
IMPORTANT! Product reviews require the extra research fee.
<br/>

<%= simple_form_for @request_article do |f| %>
  <%= f.input :keywords %>
  <%= f.input :exact_kewords ,label: 'Use my EXACT KEYWORDS in the article (otherwise the keywords will be treated as a general topic). If Exact Keywords are requested, each article will have the keywords in the title and three times in the body (for articles of 300 words or more; shorter articles will contain the keywords at least once in the body). ' %>
  <%=f.input :article_instruction,label:'Article Instructions and Details: (Optional)
Describe the angle or slant you want the article to have and give any additional article style and format requirements.Only available if you pay the style fee. [ Why? ]' %>
  <%=f.input :no_of_article ,collection: 1..10%>
  <%=f.input :word_count ,collection: %w[100 200 300 400 500 600 700 800 900 1000]%>
  <%=f.input :fixed_delivery_time,label: 'Guaranteed 24-hour delivery. (+$0.30/100 words) [?] ' %>
  <%=f.input :writer_stars, label:'Guaranteed four or five-star writers only. (+$0.30/100 words) [?] ' %>
  <%=f.input :depth_research,label:'In-depth research stipend. (+$0.30/100 words) [?]' %>
  <%=f.input :specific_style ,label:'Extra fee to allow specific article style requests in the instructions. (+$0.30/100 words) [?]'%>
  <%#=f.input :terms_and_conditions,label:'I understand and agree to the terms of service for article requests. ' %>
  <%=f.input :article_topic_warning, label:'None of my article keywords fall into any of the following categories: adult, gambling, hate, illegal activites. Submitting any requests in those categories may result in your account being permanently closed and your PayPal account banned from funding any other accounts. ' %>
  <%= f.button :submit,'submit request' %>
<% end %>
</div>

app/views/articles/show.html.erb
<h1>Completed Articlese</h1>
<br/>
<br/>
Keywords:
<br/>
<br/>
<b>Word Count:	<%=count_words(@article.content)%></b>
<br/>
<br/>
<p>
<%= @article.content%>
</p>

app/views/articles/update.html.erb
%h1 Articles#update
%p Find me in app/views/articles/update.html.haml