config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do
    
  root 'pages#home'

  ActiveAdmin.routes(self)
  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix
  devise_for :users, path: devise_prefix,
    controllers: {registrations: 'users/registrations', sessions: 'users/sessions',
      passwords: 'users/passwords', confirmations: 'users/confirmations', unlocks: 'users/unlocks'},
    path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}
  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
  end
  get devise_prefix => redirect('/#account')
  post devise_prefix => redirect('/#account')

  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'
  get '/terms' => 'pages#terms', as: 'terms'
  get '/privacy' => 'pages#privacy', as: 'privacy'
  get '/billing' => 'pages#billing', as: 'billing'
  get '/cookies' => 'pages#cookies', as: 'cookies'
  get '/copyright' => 'pages#copyright', as: 'copyright'
  get '/earnings' => 'pages#earnings', as: 'earnings'
  get '/spam' => 'pages#spam', as: 'spam'

  # OAuth
  oauth_prefix = Rails.application.config.auth.omniauth.path_prefix
  get "#{oauth_prefix}/:provider/callback" => 'users/oauth#create'
  get "#{oauth_prefix}/failure" => 'users/oauth#failure'
  get "#{oauth_prefix}/:provider" => 'users/oauth#passthru', as: 'provider_auth'
  get oauth_prefix => redirect("#{oauth_prefix}/login")

  # User
  resources :users, path: 'u', only: :show do
    resources :authentications, path: 'accounts'
  end
  get '/dashboard' => 'articles#index', as: 'user_home'

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  get 'robots.:format' => 'robots#index'

  resources :articles do 
   member do
       get :download
       get :archive
     end
     collection do 
      get :index_archive
     end
  end

  resources :users
  
end

app/views/layouts/_account_tabs.html.haml
%ul.nav.nav-tabs
  %li{class: request.original_fullpath == edit_user_registration_path ? 'active' : ''}
    = link_to I18n.t('account.edit.link'), edit_user_registration_path
  %li{class: request.original_fullpath == user_authentications_path(current_user) ? 'active' : ''}
    = link_to I18n.t('auth.edit.link'), user_authentications_path(current_user)

app/views/layouts/_airbrake.html.haml
- if defined?(Airbrake) && Airbrake.configuration.js_api_key.present?
  = airbrake_javascript_notifier

app/views/layouts/_analytics.html.haml
- if Rails.application.config.analytics.google.id
  - content_for :on_ready do
    :plain
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', '#{Rails.application.config.analytics.google.id}']);
      _gaq.push(['_trackPageview']);
      $(document).on('page:change', function(){
        _gaq.push(['_trackPageview'])
      });

app/views/layouts/_banner.html.haml
- if !current_user and (current_page?(root_path) or current_page?(new_user_session_path))
  %section{id: 'banner-content'}
    .container
      .row
        .col-lg-6
          %i
            Quality Custom
          %b
            Articles
          %u
            At Affordable Prices
        .col-lg-5.col-lg-offset-1
          %ul
            %li
              Buy custom written articles online
            %li
              Professional Creative Writers
            %li
              Plagiarism-Free Content
            %li
              Only Affordable Articles
            %li
              Fast Turn Around
            %li
              Get a Quote for Your Order
            %li
              Free revisions
            %li
              Great discounts

  - if current_page?(root_path)
    %section{id: 'login-area'}
      .container
        .row
          .col-lg-12
            %a{href: new_user_session_path, class: 'btn btn-default Member Login'}
              %b
                Member Login
              Already have an account

            %a{href: '/#account', class: 'btn btn-default account'}
              %b
                Create Account
              Create Your FREE Account Now

app/views/layouts/_destroy_modal.html.haml
- id ||= 'destroy-modal'
- i18n_prefix = i18n_prefix.present? ? "#{i18n_prefix}." : ''

.modal.fade{id: id, tabindex: -1, role: 'dialog', 'aria-labelledby' => "#{id}-title", 'aria-hidden' => true}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{data: {dismiss: 'modal'}, 'aria-hidden' => true} &times;
        %h4{id: "#{id}-title"}= I18n.t "#{i18n_prefix}prompt"
      .modal-body
        - warning = I18n.t "#{i18n_prefix}warning"
        - if warning.present?
          .alert.alert-danger
            %i.glyphicon.glyphicon-warning-sign.text-danger
            = warning
        %p= I18n.t "#{i18n_prefix}notice"
      .modal-footer
        %button.btn.btn-danger{data: {confirm: '', dismiss: 'modal'}}= I18n.t "#{i18n_prefix}submit"
        %button.btn.btn-default{data: {dismiss: 'modal'}}= I18n.t "#{i18n_prefix}cancel"

app/views/layouts/_footer.html.haml
%footer{class: 'col-lg-12 col-sm-12'}
  .container
    .row
      .col-lg-5.col-sm-5
        .col-lg-4
          = image_tag('footer-logo.png')
        .col-lg-8.copyright
          = "© 2014 Buyar Aicles Fast. All rights reserved."

      .col-lg-7.col-sm-7
        %ul
          %li= link_to 'Terms of Service', terms_path
          %li= link_to 'Privacy Policy', privacy_path
          %li= link_to 'Earnings Disclaimer', earnings_path
          %li= link_to 'Copyright Notice', copyright_path
          %li= link_to 'Billing Policy', billing_path
          %li= link_to 'Cookies Policy', cookies_path

app/views/layouts/_header.html.haml
%header
  .container
    .row
      .col-lg-3.col-sm-5.col-md-5
        = link_to(image_tag("logo1.png", :alt => "") ,"/")
      .col-lg-5.col-sm-7.col-lg-offset-4.col-md-5.col-md-offset-2.no-space
        - unless user_signed_in?
          = link_to '/#account', class: "btn btn-default btn-register" do
            %span{class: 'login'}= I18n.t('auth.signup.link')
          - unless current_page?(new_user_session_path) 
            = link_to new_user_session_path ,class: "btn btn-default btn-login" do
              %span{class: 'register'}= I18n.t('auth.login.link')
        - else
          - if current_user.is_admin? or current_user.is_writer?
            = link_to '/admin', class: "btn btn-default btn-register" do
              %span{}= I18n.t('auth.admin.link')
          = link_to destroy_user_session_path ,class: "btn btn-default btn-register" do
            %span{class: 'register'}= I18n.t('auth.logout.link')

        %span{class: 'social'}
          =link_to(image_tag('icon-in.png'), "#{Rails.application.config.settings.social.linkedin}", target: '_blank')
          =link_to(image_tag('icon-fb.png'), "#{Rails.application.config.settings.social.facebook}", target: '_blank')
          =link_to(image_tag('icon-g+.png'), "#{Rails.application.config.settings.social.google_plus}", target: '_blank')
          =link_to(image_tag('icon-tiwtter.png'), "#{Rails.application.config.settings.social.twitter}", target: '_blank')

app/views/layouts/_javascripts.html.haml
-# JavaScripts included in <body> for initializing Backbone views, etc.

-# Immediately executable javascript
- if content_for? :javascript
  = yield :javascript

-# Document ready javascript
- if content_for? :on_ready
  :javascript
    head.ready(function(){
      #{yield :on_ready}
    })

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String) and msg.present?
    - type = (['info', 'success', 'warning', 'danger'].include?(name.to_s) ? name : 'info')
    .alert.alert-dismissable{class: "alert-#{type}"}
      %button.close{'data-dismiss' => 'alert', 'aria-hidden' => true} &times;
      = msg

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse{role: 'navigation'}
  .navbar-header
    %button.navbar-toggle{type: 'button', data: {toggle: 'collapse', target: '.navbar-collapse'}}
      %span.sr-only
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to I18n.t('brand.name'), root_path, class: 'navbar-brand'
  - if user_signed_in?
    %ul.nav.navbar-nav
      %li.active
        = link_to "Dashboard", articles_path
      %li
        = link_to "Request", new_article_path 
      %li
        %a{href: "#"} Add Funds
  .collapse.navbar-collapse
    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        %li.dropdown
          %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}}
            = render 'users/avatar', size: :tiny
            %b.caret
          %ul.dropdown-menu
            - if current_user.is_admin? or current_user.is_writer? 
              %li= link_to I18n.t('admin.link'), rails_admin_path, data: {"no-turbolink" => true}
            %li= link_to I18n.t('account.edit.link'), edit_user_registration_path
            %li= link_to I18n.t('auth.logout.link'), destroy_user_session_path, rel: :nofollow
      - unless user_signed_in?
        %li= link_to I18n.t('auth.signup.link'), new_user_registration_path
        %li= link_to I18n.t('auth.login.link'), new_user_session_path

app/views/layouts/_newsletter.html.haml
%section{id: 'about-content'}
  .container
    .row
      .col-lg-9.col-sm-9
        %h6= "About Us"
        .col-lg-3.col-sm-3
          = image_tag('about.png', class: 'img-responsive')
        .col-lg-9.col-sm-9
          %span 
            Buyar Aicles Fast.com Run By A Trusted Name
            %br
            In Internet Marketing
          %h5="John Doe"
          %p
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec orci nec tortor adipiscing sagittis. Mauris eleifend semper           orci, ac ultrices dui lacinia ac. Fusce id tristique quam, nec tincidunt enim. Suspendisse aliquam purus posuere iaculis                feugiat. Nam vel vulputate mauris. Pellentesque velit ipsum, placerat sed euismod ut, bibendum non massa. Cras in lacus a augue             cursus molestie. Morbi bibendum arcu felis, quis suscipit urna accumsan eget.
            %a{href: '#'} 
              Read More

      .col-lg-3.col-sm-3.spacing
        %h6="Subscribe to Newslerrer"
        %span
          Enter your email address to subscribe
          %br
          to our Newsletter
        .form-group        
          %input{type: "password", class: 'form-control subcribe', id: 'inputPassword'}
        %a{href: '#', class: 'btn btn-default subcribe'}= "Subscribe"
        %b="Follow us on"
        %span{class: 'social'}
          =link_to(image_tag('icon-in.png'), "#{Rails.application.config.settings.social.linkedin}", target: '_blank')
          =link_to(image_tag('icon-fb.png'), "#{Rails.application.config.settings.social.facebook}", target: '_blank')
          =link_to(image_tag('icon-g+.png'), "#{Rails.application.config.settings.social.google_plus}", target: '_blank')
          =link_to(image_tag('icon-tiwtter.png'), "#{Rails.application.config.settings.social.twitter}", target: '_blank')

app/views/layouts/application.html.haml
!!!
%html.no-js{lang: 'en'}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: 'width=device-width, initial-scale=1.0', name: 'viewport'}
    %title= content_for?(:title) ? yield(:title) : I18n.t('brand.name')
    %meta{content: (content_for?(:description) ? yield(:description) : I18n.t('brand.name')), name: 'description'}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    /[if lt IE 9]
      = javascript_include_tag 'ie', 'data-turbolinks-track' => true
    = javascript_include_tag 'head', 'data-turbolinks-track' => true
    = headjs_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = yield :head
  %body{class: "controller__#{controller_name} action__#{action_name}"}
    %section{id: 'wrapper', class: "#{(current_user.present?) ? 'wrapper-short' : ''}"}
      = render 'layouts/header'
      = render 'layouts/banner'
    .clearfix  
    - if user_signed_in?
      %nav.navbar.navbar-default{role: "navigation"}
        .navbar-header
          .navbar-brand{href: "#"} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        %div
          %ul.nav.navbar-nav.list-nav
            %li
              = link_to "Dashboard", articles_path,class: "title_header"
            %li
              = link_to "Request", new_article_path ,class: "title_header"
            %li
              %a{href: "#",class: "title_header"} Funds 
            %li
              %a{href: "#",class: "title_header"} SVN
    %section{id: 'main-content'}
      .container
        .errors__container
          = render 'layouts/messages'
      = yield

      - unless current_user
        = render 'layouts/newsletter'

      - if content_for? :footer
        = yield :footer
      - else
        = render 'layouts/footer'
    = render 'layouts/analytics'
    = render 'layouts/javascripts'

app/views/layouts/uncaught_error.js.haml
:plain
  var $wrap = $('.errors__container').empty()
  $wrap.append('#{escape_javascript(render 'layouts/messages')}')
  if ($wrap.length && typeof $.scrollTo == 'function') {
    $.scrollTo($wrap.offset().top - parseInt($('body').css('padding-top')), 300)
  }